alert.button.okay=Okay
alert.button.apply=Accept
alert.button.cancel=Cancel
alert.button.close=Close
alert.button.yes=Yes
alert.button.no=No
alert.button.next=Next
alert.button.continue=Continue
alert.button.back=Back

button.on=On
button.off=Off
button.exit.label=Exit
button.open.label=Open
button.save.label=Save
button.prefs.label=Preferences
button.search.label=Search Key

button.viewdetails.label=View Details
button.viewreport.raw.label=View Report (HTML Only)
button.viewreport.iframe.label=View Report (IFrame)
button.viewreport.vizjs.label=View Report (Visualize.js)
button.publishResource.label=Save & Republish Resource
button.deleteResource.label=Delete Resource

menu.connect.label=Connect JRS
menu.disconnect.label=Disconnect JRS
menu.options.label=Settings

button.add.label=Add key
options.escape.button.label=Automatic escaping
options.escape.method.label=Escape method
options.viewraw.label=View RAW

prompt.keysfield=Enter key...

combo.escape.default=Choose...
combo.escape.unicode=Default (Unicode)
combo.escape.base64=Base64
combo.escape.url=URL-Escape